### ISSUE TITLE
Adding option for selected notes

### ISSUE THREAD

**Issue by samely** [JOSM/osm-obj-info#1]
@Rub21 
This plugin is really helpful while doing Map-feedback, because you can easily copy and paste the link of updated features with just one click, however, it would be also good to add the functionality to get the link for notes.

![image](https://cloud.githubusercontent.com/assets/10425629/21813383/0c6b8b32-d724-11e6-854d-afd0e29d4471.png)

cc. @nikhilprabhakar @RichRico @dannykath @karitotp

**Comment by Rub21** [comment]
@samely , nice!,  you are in good position to add this functionality, go ahead

**Comment by samely** [comment]
I've added this [functionality](https://github.com/mapbox/osm-obj-info/pull/2)

**Comment by samely** [comment]
It's ready now, just update the plugin osm-obj-info from the list of plugins

![ns](https://cloud.githubusercontent.com/assets/10425629/21857676/446b9d8a-d7f4-11e6-8b6c-ad5e4014109f.png)


![anim](https://cloud.githubusercontent.com/assets/10425629/21857338/14678fbe-d7f3-11e6-8564-4f38c3f82a62.gif)

cc @nikhilprabhakar

**Comment by unsungNovelty** [comment]
This is soooooooooo awesome @samely! I just used it and it makes our map feedback session way easier.

@Fa7C0n @karitotp @RichRico @dannykath - Let's make sure we use this `plugin` while working on Map-feedback to improve the efficiency.

Thanks once again @samely
