### ISSUE TITLE
Update to latest JOSM

### ISSUE THREAD

**Issue by don-vip** [JOSM/osm-obj-info#6]
We have removed a lot of deprecated API as advertised on the mailing list, see https://josm.openstreetmap.de/ticket/15310

As a result this plugin is no longer compatible, can you please update it?

Thanks.

**Comment by don-vip** [comment]
@mapbox @Rub21 @samely @yudistrange can you please update this plugin soon?

**Comment by don-vip** [comment]
I have deleted osm-obj-info.jar from OSM SVN as it is not hosted there, but here. Please update the plugin and use the Github releases mechanism, then update https://josm.openstreetmap.de/wiki/PluginsSource if you want the plugin to appear in the default list. But default plugins MUST be maintained, which is not exactly how I would describe MapBox plugins...

**Comment by yudistrange** [comment]
Hi @don-vip 

We had updated the plugin to remove dependency on the deprecated APIs. I compiled and tested `osm-obj-info` jar against the latest JOSM code base. There don't seem to be any compile time warnings/errors. I tested the plugin locally and it is working fine. Is there any other way to validate this? 

Thanks!

**Comment by don-vip** [comment]
If there's no warning you're good to go. You can publish it and list the jar on the wiki.

**Comment by Klumbumbus** [comment]
It seems the new version wasn't published? Latest version is still 1505407450
New report at https://josm.openstreetmap.de/ticket/15724

**Comment by Klumbumbus** [comment]
I just noticed that this plugin is not at all at https://josm.openstreetmap.de/wiki/PluginsSource. Version 1505407450 is my local cache file. However there is no way for an automatic update.

**Comment by don-vip** [comment]
Yes plugin has not been updated yet. Mapbox gave us the repositories too late.  Now we can update all these plugins: https://github.com/orgs/JOSM/teams/mapbox/repositories

**Comment by don-vip** [comment]
Fixed in v1.0
